[package]
name = "ballista"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
ballista = { version = "0.12" }
datafusion = "41.0.0"
tokio = { version = "1.37", features = ["full"] }
