[package]
name = "ballista"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
ballista = { version = "0.11" }
datafusion = "19.0.0"
tokio = { version = "1.26", features = ["full"] }
